package com.aft.common.enums;

public enum ActionType {
    NAVIGATE,NAVIGATE_BACK,NAVIGATE_FORWARD,REFRESH,
    CLICK,DOUBLE_CLICK,RIGHT_CLICK,MIDDLE_CLICK,HOVER,DRAG_AND_DROP_CLICK_AT_OFFSET,
    TYPE,TYPE_SECRET,CLEAR,SELECT_OPTION,PRESS_KEY,PRESS_KEY_COMBO,UPLOAD_FILE,FOCUS,BLUR,
    SCROLL_TO_ELEMENT,SCROLL_TO_TOP,SCROLL_TO_BOTTOM,SCROLL_TO_PIXELS,
    WAIT_SECONDS, WAIT_FOR_VISIBLE, WAIT_FOR_INVISIBLE, WAIT_FOR_CLICKABLE,WAIT_FOR_TEXT, WAIT_FOR_URL,
    ASSERT_VISIBLE, ASSERT_NOT_VISIBLE, ASSERT_TEXT_EQUALS, ASSERT_TEXT_CONTAINS,
    ASSERT_TEXT_MATCHES_REGEX, ASSERT_URL_EQUALS, ASSERT_URL_CONTAINS,
    ASSERT_TITLE_CONTAINS, ASSERT_ATTRIBUTE_EQUALS, ASSERT_ELEMENT_COUNT,
    ASSERT_ENABLED, ASSERT_DISABLED,
    SWITCH_FRAME, SWITCH_TO_PARENT_FRAME, SWITCH_TO_DEFAULT_CONTENT, SWITCH_TAB, OPEN_NEW_TAB, CLOSE_TAB,
    SET_COOKIE, DELETE_COOKIE, CLEAR_COOKIES, SET_LOCAL_STORAGE, CLEAR_LOCAL_STORAGE,
    SCREENSHOT, EXECUTE_SCRIPT, LOG_MESSAGE, SLEEP_RANDOM,

    INCLUDE_SCENARIO


}
